### ISSUE TITLE
Enhance NHL with Roster Add and Edit

### ISSUE THREAD

**Issue by smagara** [smagara/AgilitySports_web#29]
Add CRUD capability to NHL roster grid.  Utilize Copilot as necessary.
Steps (sub-issues)

- [x] smagara/AgilitySports_api#14
- [x] smagara/AgilitySports_web#31
- [x] smagara/AgilitySports_web#32
- [x] smagara/AgilitySports_data#4

**Comment by smagara** [comment]
All tasks done under associated sub-Issues.
More Issues incoming for additional findings as validation continues
