### ISSUE TITLE
Implement NBA CRUD

### ISSUE THREAD

**Issue by smagara** [smagara/AgilitySports_web#50]
Implement CRUD for the NBA Roster grid.  Consider mirroring the functionality implemented for the NHL Roster.  

Subissues will track each expected sub-task.

- [x] smagara/AgilitySports_api#16
- [x] smagara/AgilitySports_web#52
- [x] smagara/AgilitySports_web#53

**Comment by smagara** [comment]
All subitems completed, closing subissues tracker
